### ISSUE TITLE
Checklist: v2 Relaunch Testing

### ISSUE THREAD

**Issue by manaswis** [ProjectSidewalk/SidewalkWebpage#687]
This list needs to be updated to capture all the testing that needs to be done for recent changes made in the past month. Starting it with some things that I can remember. Needs to be further updated by everyone. 
- Please update based on the issues you have worked on: @maddalihanumateja @misaugstad @sbower213 @adash12 @chishankar @sagec108 
- Link the issues numbers when you update this list

### Browser Compatibility Issues
**Desktop**
To be tested on Chrome, Safari, Firefox, Edge
- [ ] Check if the label icons are displayed on the canvas properly (related to #316).
- [ ] Panning works on all browsers
- [ ] Zooming controls (PR #650)
     - [ ] Shift+Z: zooms out, Z: zooms in (#623)
     - [ ] Zooming out, by tool buttons, work as intended
     - [ ] Zooming in any manner does not break context menu/label appearances 
- [ ] New updates to onboarding tutorial
- [ ] Performance issues (CPU/memory usage)
- [ ] Logging anoymous user to registered user transition
- [ ] Loading/Hiding audit interface after the mission text is shown

**Mobile**
To be tested on browsers - Safari, Chrome, webkit on OSs - iOS and Android
- [ ] Mobile landing page shown properly (#607)
- [ ] Visits from mobile is logged correctly in the database.

### New Updates
- [ ] Onboarding
     - [ ] New zoom-in stage (#541)
     - [ ] Walk tutorial (#228)
     - [ ] Label counter reset after onboarding ends (#498)
     - [ ] All yellow arrows now flash (#453)
     - [ ] Two curb ramp corner - order disabled (#542)
     - [ ] All interactions disabled except the step the ones relevant to the stage is on (e.g. can't use Surface problem label when you are supposed to apply missing curb ramp)
     - [ ] New instructions after the walk tutorial with messages colocated with the items being discussed; shown with animations
     - [ ] Corrective guidance when the user applies label in the wrong position
     - [ ] Restrict panning/Corrective guidance on wrong panning direction
     - [ ] Updated step to tell users to pan before reaching the two curb ramp corner position (#543)
- [ ] Admin Dashboard (issue #342  PR #692 )
     - [ ] Overview tab: Coverage table, "Rate" is now a column instead of a row
     - [ ] Analytics tab: Check that choropleth works correctly
     - [ ] Analytics tab: Check that every title heading has an appropriate graph under it
     - [ ] Analytics tab: Check that button correctly switches sorting order of neighborhoods in chart
- [ ] Audit interface
     - [ ] User points in the same direction as the route after jumps (Issue #334 , PR #660 )
     - [ ] Pop-up messages disable any interactions with the tool until they are hidden (PR #671)
     - [ ] Sign up/Sign in dialogues disable tool interactions while visible
     - [ ] Label icon changes without requiring mouse movement (issue #613, PR #659)
- [ ] Optimization of landing page (CPU and memory usage)
- [ ] Choropleth added to landing page (issue #697 PR #692 )
- [ ] Admin page performance optimization - CPU and memory usage - (IF DONE)
- [ ] Resolved OutOfMemory Issue (by disabling audit interaction data)
- [ ] Unique emails and usernames required for sign-in (Issue #488 , PR #665 )
- [ ] DC coverage on landing page now calculated using distance (issue #676, PR #692 )
- [ ] Enhanced readibility of "What is Project Sidewalk?" on landing screen (issue #576, PR #699)
- [ ] Updated "Sign In" text (issue #609, PR #667)

**Comment by manaswis** [comment]
Also, along with issue numbers, also add the PR numbers too. The PRs usually have description of the things changed and things that need testing.
